#Arrays 
You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

In [1]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    b=numpy.array(arr, float)
    return b[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


#Shape and Reshape
You are given a space separated list of nine integers. Your task is to convert this list into a 3 X 3 NumPy array.

In [2]:
import numpy
lst= input().split(' ')
lst=numpy.array(lst, int)
lst.shape=(3,3)
print(lst)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#Transpose and Flatten
You are given a N X M integer array matrix with space separated elements (N = rows and M = columns).
Your task is to print the transpose and flatten results.

In [3]:
import numpy
n,m= map(int, input().split(" "))
arr = numpy.array([input().split() for i in range(n)], int)
print(arr.transpose())
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


#Concatenate
You are given two integer arrays of size N X P and M X P (N & M  are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

In [5]:
import numpy
n,m,p= map(int, input().split(" "))
arr_n = numpy.array([input().strip().split() for i in range(n)], int)
arr_m = numpy.array([input().strip().split() for i in range(m)], int)
print(numpy.concatenate((arr_n, arr_m), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


#Zeros and Ones
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

In [6]:
import numpy
arr_size= tuple(map(int, input().split(" ")))
print(numpy.zeros(arr_size, dtype=numpy.int))
print(numpy.ones(arr_size, dtype= numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


#Eye and Identity
Your task is to print an array of size N X M with its main diagonal elements as 1's and 0's everywhere else.

In [7]:
import numpy
numpy.set_printoptions(legacy='1.13')
n,m= map(int, input().strip().split(" "))
print(numpy.eye(n,m, k=0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#Array Mathematics
You are given two integer arrays, A and B of dimensions N X M.
Your task is to perform the following operations:

Add (A + B)
Subtract ( A - B )
Multiply ( A * B )
Integer Division (A / B)
Mod ( A % B )
Power ( A ** B)

In [8]:
import numpy
n,m= map(int, input().strip().split(" "))
arr_n = numpy.array([input().strip().split() for i in range(n)], int)
arr_m = numpy.array([input().strip().split() for i in range(n)], int)
print(arr_n+ arr_m)
print(arr_n - arr_m)
print(numpy.multiply(arr_n, arr_m))
print(numpy.floor_divide(arr_n, arr_m))
print(arr_n% arr_m)
print(arr_n ** arr_m)

1 4
1 2 3 4
5 6 7 8 
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


#Floor, Ceil and Rint
You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A .

In [9]:
import numpy
numpy.set_printoptions(legacy='1.13')
n= numpy.array((input().strip().split(" ")), dtype=float)
print(numpy.floor(n))
print(numpy.ceil(n))
print(numpy.rint(n))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


#Sum and Prod
You are given a 2-D array with dimensions N X M.
Your task is to perform the sum tool over axis 0 and then find the product of that result.

In [10]:
import numpy
n,m= map(int, input().strip().split(" "))
arr_n = numpy.array([input().strip().split() for i in range(n)], int)
np_sum=numpy.sum(arr_n, axis=0)
print(numpy.product(np_sum))

2 2
1 2
3 4
24


#Min and Max
You are given a 2-D array with dimensions N X M.
Your task is to perform the min function over axis 1 and then find the max of that.

In [11]:
import numpy
n,m= map(int, input().strip().split(" "))
arr_n = numpy.array([input().strip().split() for i in range(n)], int)
np_min=numpy.min(arr_n, axis=1)
print(numpy.max(np_min))

4 2 
2 5
3 7
1 3
4 0
3


#Mean, Var, and Std
You are given a 2-D array of size N X M.
Your task is to find:

The mean along axis 1
The var along axis 0
The std along axis None

In [12]:
import numpy
n,m= map(int, input().strip().split(" "))
arr=numpy.array([input().strip().split() for _ in range(n)], int)
print(numpy.mean(arr, axis=1))
print(numpy.var(arr, axis=0))
print(round(numpy.std(arr, axis=None), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


#Dot and Cross
You are given two arrays A and B. Both have dimensions of N X N.
Your task is to compute their matrix product.

In [13]:
import numpy
n=int(input())
arr_n = numpy.array([input().strip().split() for i in range(n)], int)
arr_m = numpy.array([input().strip().split() for i in range(n)], int)
print(numpy.dot(arr_n, arr_m))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


#Inner and Outer
You are given two arrays: A and B .
Your task is to compute their inner and outer product.

In [14]:
import numpy
arr_n = numpy.array(input().strip().split(), int)
arr_m = numpy.array(input().strip().split(), int)
print(numpy.inner(arr_n, arr_m))
print(numpy.outer(arr_n, arr_m))

0 1
2 3
3
[[0 0]
 [2 3]]


#Polynomials
You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x .

In [15]:
import numpy
arr_p = numpy.array(input().strip().split(), float)
x=int(input())
print(numpy.polyval(arr_p, x))

1.1 2 3
0
3.0


#Linear Algebra
You are given a square matrix A with dimensions N X N. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

In [17]:
import numpy
n=int(input())
arr_p = numpy.array([input().strip().split() for _ in range(n)], float)
print(round(numpy.linalg.det(arr_p),2))

2
1.1 1.1
1.1 1.1
0.0
